insert into charities (category, charity_name, ein, description, city, state)
values


 # Animal Welfare
  ('Animal Welfare', 'American Bird Conservancy', '52-1501259', 'Conserves native wild birds and their habitats throughout the Americas, safeguarding the rarest species, restoring habitats, and reducing threats, while building capacity in the bird conservation movement.', 'The Plains', 'Virginia'),
  ('Animal Welfare', 'Animal Welfare Institute', '13-5655952', 'To alleviate the suffering of animals caused by people.', ' Washington', 'DC'),
  ('Animal Welfare', 'Dian Fossey Gorilla Fund International', '52-1118866', 'Dedicated to the conservation of gorillas and their habitats in Africa. Committed to promoting continued research on their threatened ecosystems and education about their relevance to the world in which we live.', 'Atlanta', 'Georgia'),
  ('Animal Welfare', 'PetSmart Charities', '93-1140967', 'Saves wildlife & wild places worldwide through science, conservation action, education, and inspiring people to value nature.', 'Phoenix', 'Arizona'),
  ('Animal Welfare', 'Wildlife Conservation Society', '13-1740011', 'Saves wildlife & wild places worldwide through science, conservation action, education, and inspiring people to value nature.', 'Bronx', 'New York'),

  # Cancer
  ('Cancer', 'Breast Cancer Research Foundation', '13-3727250', 'To prevent and cure breast cancer by advancing the world\'s most promising research.', 'New York', 'New York'),
  ('Cancer', 'Cancer Research Institute', '13-1837442', 'To save more lives by fueling the discovery and development of powerful immunotherapies for all types of cancer.', 'New York', 'New York'),
  ('Cancer', 'LiveStrong Foundation', '74-2806618', 'Dedicated to enhancing the quality of life for those living with, through and beyond cancer by supporting scientific research, educational community programs and in public awareness efforts.', 'Austin', 'Texas'),
  ('Cancer', 'Multiple Myeloma Research Foundation', '06-1504413', 'To relentlessly pursue innovative means to accelerate collaborative scientific discoveries and the development of break through multiple myeloma treatments to extend and improve the lives of patients and lead to a cure.', 'Norwalk', 'Connecticut'),
  ('Cancer', 'Ovarian Cancer Research Fund Alliance', '13-3806788', 'To fund scientific research that leads to more effective identification, treatment, and ultimately a cure for ovarian cancer, as well as related educational and support initiatives.', 'New York', 'New York'),
  ('Cancer', 'Pancreatic Cancer Action Network', '33-0841281', 'To advance research, support patients, and create hope for people who have pancreatic cancer.', 'Manhattan Beach', 'Califronia'),
  ('Cancer', 'Prostate Cancer Foundation', '95-4418411', 'Committed to ending death and suffering from prostate cancer; accelerates the world\'s most promising prostate cancer research with the goal of developing new precision medicines and cures for prostate cancer.', 'Santa Monica', 'California'),

  # Child Protection, Sponsorship, and Youth Development
  ('Child Protection, Sponsorship, and Youth Development', 'Boys and Girls Clubs of America (National Office)', '13-5562976', 'To enable all young people, especially those who need us most, to reach their full potential as productive, caring, responsible citizens.', 'Atlanta', 'Georgia'),
  ('Child Protection, Sponsorship, and Youth Development', 'Big Brothers/Big Sisters of America (National Office)', '23-1365190', 'To provide children facing adversity with strong and enduring, professionally supported 1-to-1 relationships that change their lives for the better, forever.', 'Tampa', 'Florida'),
  ('Child Protection, Sponsorship, and Youth Development', 'Child Find of America', '22-2323336', 'To prevent and resolve all cases of missing, abducted and runaway children.', 'New Paltz', 'New York'),
  ('Child Protection, Sponsorship, and Youth Development', 'Children\'s Defense Fund', '52-0895622', 'To ensure every child a healthy start, a head start, a fair start, a safe start, and a moral start in life and successful passage to adulthood.', 'Washington', 'DC'),
  ('Child Protection, Sponsorship, and Youth Development', 'DonorsChoose.org', '13-4129457', 'Engages the public in public schools by giving people a simple, accountable and personal way to address educational inequity; envision a nation where children in every community have the tools and experiences needed for an excellent education.', 'New York', 'New York'),
  ('Child Protection, Sponsorship, and Youth Development', 'Girls Incorporated (National Office)', '13-1915124', 'Inspires all girls to be strong, smart, and bold through life-changing programs and experiences that help girls navigate gender, economic, and social barriers.', 'New York', 'New York'),
  ('Child Protection, Sponsorship, and Youth Development', 'Prevent Child Abuse America (National Office', '23-7235671', 'To prevent the abuse and neglect of our nation\'s children.', 'Chicago', 'Illinois'),
  ('Child Protection, Sponsorship, and Youth Development', 'Save the Children', '06-0726487', 'To inspire breakthroughs in the way the world treats children, and to achieve immediate and lasting change in their lives.', 'Fairfield', 'Connecticut'),
  ('Child Protection, Sponsorship, and Youth Development', 'Starlight Children\'s Foundation (National Office)', '95-3802159', 'Partners with experts to improve the life and health of kids and families around the world.', 'Los Angelese', 'California'),
  ('Child Protection, Sponsorship, and Youth Development', 'Unbound', '43-1243999', 'Provides financial support, services and encouragement to individuals and their families living on the margins of society around the world.', 'Kansas City', 'Kansas'),
  ('Child Protection, Sponsorship, and Youth Development', 'The Y (National Office)', '36-3258696', 'To serve as the national resource office for the nation\'s Ys, which strengthen community by nurturing the potential of kids, promoting healthy living for all, and fostering social responsibility.', 'Chicago', 'Illinois'),

#Education and Scholarship
  ('Education and Scholarship', 'American Indian College Fund', '52-1573446', 'Transforms Indian higher education by funding and creating awareness of the unique, community-based accredited tribal colleges and universities, offering students access to knowledge, skills and cultural values which enhance their communities and the country as a whole.', 'Denver', 'Colorado'),
  ('Education and Scholarship', 'Center for Creative Education', '65-0594599', 'The Center for Creative Education uses the arts to enrich and transform a child\'s educational experience. We use visual, performing and language arts to enhance children\'s knowledge of literacy, math and science. We help bring learning to life!', 'West Palm Beach', 'Florida'),
  ('Education and Scholarship', 'Excelencia in Education', '20-0927912', 'Excelencia in Education accelerates Latino student success in higher education by providing data-driven analysis of the educational status of Latinos, and by promoting education policies and institutional practices that support their academic achievement. ', 'Washington', 'DC'),
  ('Education and Scholarship', 'Hispanic Scholarship Fund', '52-1051044', 'Providing the Hispanic community and other minorities college scholarships and educational outreach support.', 'Gardena', 'California'),
  ('Education and Scholarship', 'Scholarship America', '04-2296967', 'To mobilize America through scholarships and educational support to make post-secondary education possible for all students.', 'Saint Peter', 'Minnesota'),

# Environment
  ('Environment', 'Conservation Fund', '52-1388917', 'Working with public, private and nonprofit partners, protects America\'s legacy of land and water resources through land acquisition, sustainable community and economic development, and leadership training.', 'Arlington', 'Virginia'),
  ('Environment', 'Environmental Defense Action Fund (Advocacy partner of EDF)', '90-0080500', 'To educate the public regarding environmental and conservation issues, and advocate legislation and policies that protect the environmental rights of all people.', 'New York', 'New York'),
  ('Environment', 'Earthjustice', '94-1730465', 'Uses the law to protect natural heritage, safeguard health, and promote a clean energy future.', 'San Francisco', 'California'),
  ('Environment', 'Earthworks', '52-1557765', 'Protecting communities and the environment from the adverse impacts of irresponsible mineral and energy development while promoting sustainable solutions.', 'Washington', 'DC'),
  ('Environment', 'Trust for Public Land', '23-7222333', 'Creates parks & protects land for people, ensuring healthy, livable communities for generations to come. Works to ensure that everyone has access to nature within a 10-minute walk from home.', 'San Franscisco', 'California'),
  ('Environment', 'Waterkeeper Alliance', '13-4071318', 'Organized to serve as the umbrella group for programs throughout North America and in other countries; focuses on citizen advocacy on the issues that affect our waterways.', 'New York', 'New York'),

  # Human Rights, Civil Rights, and Social Responsibility
  ('Human Rights, Civil Rights, and Social Responsibility', 'American Civil Liberties Union (ACLU) Foundation', '13-6213516', 'To maintain and advance civil liberties, including, without limitation, the freedoms of association, press, religion, and speech, and the rights to the franchise, to due process of law, and to equal protection of the laws for all people throughout the United States and its jurisdictions.', 'New York', 'New York'),
  ('Human Rights, Civil Rights, and Social Responsibility', 'Amnesty International of the USA', '52-0851555', 'To act in concert with the international human rights movement, within the context of its work to promote all provisions in the universal declaration of human rights.', 'New York', 'New York'),
  ('Human Rights, Civil Rights, and Social Responsibility', 'Anti-Defamation League & Foundation', '13-1818723', 'Defending democratic ideals and eliminating anti-semitism and bigotry in the United States & around the world, while providing knowledgeable leadership on a national level for the American Jewish community.', 'New York', 'New York' ),
  ('Human Rights, Civil Rights, and Social Responsibility', 'Center for Constitutional Rights', '22-6082880', 'A legal & educational organization dedicated to advancing and protecting the rights guaranteed by the United States Constitution and the Universal Declaration of Human Rights.', 'New York', 'New York'),
  ('Human Rights, Civil Rights, and Social Responsibility', 'Common Cause Education Fund', '31-1705370', 'Nonpartisan organization dedicated to restoring the core values of American democracy, reinventing an open, honest and accountable government that serves the public interest, and empowering ordinary people to make their voices heard in the political process.', 'Washington', 'DC'),
  ('Human Rights, Civil Rights, and Social Responsibility', 'Committee to Protect Journalists', '13-3081500', 'Promotes press freedom worldwide and defends the right of journalists to report the news without fear of reprisal.', 'New York', 'New York'),
  ('Human Rights, Civil Rights, and Social Responsibility', 'Government Accountability Project (GAP)', '52-1343924', 'To promote government and corporate accountability by advancing occupational free speech, defending whistleblowers, and empowering citizen activists.', 'Washington', 'DC'),
  ('Human Rights, Civil Rights, and Social Responsibility', 'Human Rights Watch', '13-2875808', 'Dedicated to protecting the human rights of people around the world.', 'New York', 'New York'),
  ('Human Rights, Civil Rights, and Social Responsibility', 'Innocence Project', '32-0077563', 'Dedicated to exonerating innocent people through DNA testing and reforming the criminal justice system to prevent wrongful convictions.', 'New York', 'New York'),
  ('Human Rights, Civil Rights, and Social Responsibility', 'NAACP Legal Defense and Educational Fund', '13-1655255', 'To support litigation in the areas of poverty and justice, education, voting rights, fair employment, capital punishment, administration of criminal justice, and to increase educational opportunities through scholarships.', 'New York', 'New York'),
  ('Human Rights, Civil Rights, and Social Responsibility', 'National Urban League (National Office', '13-1840489', 'To enable African-American and other urban communities to secure economic self-reliance, parity, power, and civil rights.', 'New York', 'New York'),



  # Health Services
  ('Health Services', 'American Sexual Health Association', '94-2494435', 'Promote the sexual health of individuals, families & communities by advocating sound policies & practices and educating the public, professionals & policy makers, in order to foster healthy sexual behaviors & relationships and prevent adverse health outcomes.', 'Research Triangle Park', 'North Carolina'),
  ('Health Services', 'American Kidney Fund', '23-7124261', 'To fight kidney disease through direct financial support to patients in need; health education; and prevention efforts.', 'Rockville', 'Maryland'),
  ('Health Services', 'Arc of the United States (National Office)', '13-5642032', 'Promotes and protects the human rights of people with intellectual and developmental disabilities and actively supports their full inclusion and participation in the community throughout their lifetimes.', 'Washington', 'DC'),
  ('Health Services', 'Bill, Hillary & Chelsea Clinton Foundation', '31-1580204', 'Works to improve global health & wellness, increase opportunity for women & girls, reduce childhood obesity, create economic opportunity & growth, and help communities address the effects of climate change.', 'New York', 'New York'),
  ('Health Services', 'Brain & Behavior Research Foundation', '31-1020010', 'The Brain & Behavior Research Foundation is committed to alleviating the suffering caused by mental illness by awarding grants that will lead to advances and breakthroughs in scientific research.', 'New York', 'New York'),
  ('Health Services', 'Christopher & Dana Reeve Foundation', '22-2939536', 'Dedicated to curing spinal cord injury by funding innovative research and improving the quality of life for people living with paralysis through grants, information, and advocacy.', 'Short Hills', 'New Jersey'),
  ('Health Services', 'Drug Policy Alliance', '52-1516692', 'To advance those policies and attitudes that best reduce the harms of both drug use and drug prohibition, and to promote the sovereignty of individuals over their minds and bodies.', 'New York', 'New York'),
  ('Health Services', 'Elizabeth Glaser Pediatric AIDS Foundation', '95-4191698', 'To prevent pediatric HIV infections and to eradicate pediatric AIDS through research, advocacy, and prevention and treatment programs.', 'Washington', 'DC'),
  ('Health Services', 'Foundation for AIDS Research', '13-3163817', 'Dedicated to ending the global AIDS epidemic through innovative research.', 'New York', 'New York'),
  ('Health Services', 'Guide Dog Foundation for the Blind', '11-1687477', 'To assist the blind and disabled veterans & active military personnel through activities that include: breeding and training of guide & service dogs; training the blind to use these guide dogs; doing everything necessary or desirable to improve the independence of the blind; and educating the public about opportunities for the blind in our society.', 'Smithtown', 'New York'),
  ('Health Services', 'Guttmacher Institute', '13-2890727', 'To advance sexual & reproductive health & rights through an interrelated program of research, policy analysis, and communications & publications designed to generate new ideas, encourage enlightened public debate, and promote sound policy & program development.', 'New York', 'New York'),
  ('Health Services', 'Hearing Health Foundation', '13-1882107', 'To prevent and cure hearing loss and tinnitus through groundbreaking research.', 'New York', 'New York'),
  ('Health Services', 'Helen Keller International', '13-5562162', 'Save the sight and lives of the world\'s most vulnerable and disadvantaged', 'New York', 'New York'),
  ('Health Services', 'Michael J. Fox Foundation for Parkinson\'s Research', '13-4141945', 'Dedicated to ensuring the development of better treatments, and ultimately a cure, for Parkinson\'s disease through an aggressively funded research agenda.', 'New York', 'New York'),
  ('Health Services', 'National Council on Aging', '13-1932384', 'Dedicated to improving the health and independence of older persons, especially those who are vulnerable and disadvantaged.', 'Washington', 'DC'),
  ('Health Services', 'National Federation of the Blind', '02-0259978', 'Integration of the blind into society on a basis of equality through self-organization, peer support and training, change of public attitudes, advocacy, improvement of public and private services, and non-visual access technology, methods and systems.', 'Baltimore', 'Maryland'),
  ('Health Services', 'Partnership for Drug-Free Kids', '13-3413627', 'Dedicated to reducing substance abuse among adolescents by supporting families and engaging with teens.', 'New York', 'New York'),
  ('Health Services', 'Salk Institute for Biological Studies', '95-2160097', 'The advancement and dissemination of knowledge relevant to the health and well-being of man. Performs research and advanced instruction in biology; the cause, prevention, and cure of diseases; and the factors and circumstances conducive to the fulfillment of man\'s biological potential.', 'La Jolla', 'California'),
  ('Health Services', 'Seva Foundation', '38-2231279', 'Seva Foundation partners worldwide to create self-sustaining programs that preserve and restore sight.', 'Berkeley', 'California'),
  ('Health Services', 'Trevor Project', '95-4681287', 'To end suicide among lesbian, gay, bisexual, transgender and questioning (LGBTQ) young people.', 'West Hollywood', 'California'),

  # Hunger and Shelter
  ('Hunger and Shelter', 'Action Against Hunger-USA', '13-3327220', 'To save lives by eliminating hunger through the prevention, detection and treatment of malnutrition, especially during and after emergency situations of conflict, war and natural disaster.', 'New York', 'New York'),
  ('Hunger and Shelter', 'Bowery Residents\' Committee', '13-2736659', 'To meet the needs of people with low income, homeless, hungry, chemically dependent, psychiatrically disabled, aged and persons with HIV and AIDS. Provides a comprehensive array of services, including health care, vocational rehabilitation, AIDS services, community education and advocacy.', 'New York', 'New York'),
  ('Hunger and Shelter', 'Food for the Hungry', '95-2680390', 'To walk with churches, leaders and families in overcoming all forms of human poverty by living in healthy relationship with God and His creation.', 'Phoenix', 'Arizona'),
  ('Hunger and Shelter', 'Habitat for Humanity International (National Office)', '91-1914868', 'Seeking to put God\'s love into action, brings people together to build homes, communities and hope.', 'Americus', 'Georgia' ),
  ('Hunger and Shelter', 'Meals on Wheels America (National Office)', '23-7447812', 'To empower local community programs to improve the health and quality of life of the seniors they serve so that no one is left hungry or isolated.', 'Arlington', 'Virginia'),
  ('Hunger and Shelter', 'National Alliance to End Homelessness', '52-1299641', 'Preventing and ending homelessness in the United States.', 'Washington', 'DC'),

  # International
  ('International', 'Africare', '237-116952', 'Works to improve the quality of life of the people in Africa by building partnerships with African people to build sustainable, healthy and productive lives and communities, and is a leading voice in addressing African development and policy issues.', 'Washington', 'DC'),
  ('International', 'American Jewish Joint Distribution Committee', '13-1656634', 'To provide social services for Jewish people in need.', 'New York', 'New York'),
  ('International', 'American Red Cross', '53-0196605', 'Prevents and alleviates human suffering in the face of emergencies by mobilizing the power of volunteers and the generosity of donors.', 'Washington', 'DC'),
  ('International', 'American Refugee Committee', '36-3241033', 'Works with refugees, displaced people, and those at risk to help them survive crises and rebuild lives of dignity, health, security, and self-sufficiency.', 'Minneapolis', 'Minnesota'),
  ('International', 'Asia Foundation',  '94-1191246', 'Committed to the development of a peaceful, prosperous, just, and open Asia-Pacific region. Supports Asian initiatives to improve governance, law, and civil society; women\'s empowerment; economic reform and development; sustainable development and the environment; and international relations.', 'San Fransisco', 'California'),
  ('International', 'Catholic Relief Services', '13-5563422', 'The official international humanitarian agency of the Catholic community in the U.S.; provides assistance to the poor overseas without regard to race, religion or nationality by responding to emergencies and fighting poverty.', 'Baltimore', 'Maryland'),
  ('International', 'charity: water', '22-3936753', 'Bringing clean and safe drinking water to people in developing nations.', 'New York', 'New York'),
  ('International', 'Doctors Without Borders USA', '13-3433452', 'To provide independent medical humanitarian emergency aid to people affected by armed conflict, epidemics, malnutrition, natural disasters, and exclusion from health care.', 'New York', 'New York'),
  ('International', 'Global Hunger Project', '94-2443282', 'To end hunger and poverty by pioneering sustainable, grassroots, women-centered strategies and advocating for their widespread adoption in countries throughout the world.', 'New York', 'New York'),
  ('International', 'International Rescue Committee', '13-5660870', 'Helps people whose lives and livelihoods are shattered by conflict and disaster to survive, recover and gain control of their future.', 'New York', 'New York'),
  ('International', 'International Peace Institute', '03-0213226', 'Dedicated to promoting the prevention and settlement of conflicts between and within states by strengthening international peace and security institutions.', 'New York', 'New York'),
  ('International', 'Japan Society', '13-1675082', 'Committed to deepening mutual understanding between the U.S. and Japan in a global context; serves audiences across the U.S. and abroad through innovative programs in arts & culture, public policy, business, language and education.', 'New York', 'New York'),
  ('International', 'Partners in Health', '04-3567502', 'Dedicated to delivering quality health care to people and communities devastated by the joint burdens of poverty and disease. Work has three goals: to care for patients, to alleviate the root causes of disease, and to share lessons learned around the world.', 'Boston', 'Massachusetts'),
  ('International', 'Population Services International', '56-0942853', 'Measurably improve the health of the poor and vulnerable people in the developing world, principally through social marketing of family planning and health products, services, and communications.', 'Washington', 'DC'),
  ('International', 'United Methodist Committee on Relief', '13-5562279', 'Alleviating human suffering around the globe by providing humanitarian aid through programs of relief, rehabilitation, service to refugees, and renewal of life.', 'New York', 'New York'),
  ('International', 'World Vision', '95-1922279', 'Dedicated to working with children, families, and their communities to reach their full potential, in nearly 100 countries, by helping tackle the causes of poverty and injustice.', 'Federal Way', 'Washington'),

  # Veterans
  ('Veterans', 'Fisher House Foundation', '11-3158401', 'Provides military families housing close to a loved one during hospitalization for an illness, disease or injury; also funds a scholarship program for military families, and provides military personnel and their families with free air travel and hotel rooms.', 'New York', 'New York'),
  ('Veterans', 'Semper Fi Fund', '26-0086305', 'Provides immediate and long-term support for post-9/11 injured and critically ill members of the U.S. Armed Forces and their families.', 'Camp Pendleton', 'California'),
  ('Veterans', 'Homes for Our Troops', '54-2143612', 'To build mortgage free, specially adapted homes nationwide for severely injured veterans post-9/11, to enable them to rebuild their lives.', 'Taunton', 'Massachusetts'),
  ('Veterans', 'Operation Homefront', '32-0033325', 'To provide emergency financial and other assistance to the families of our service members and wounded warriors.', 'San Antonio', 'Texas'),
  ('Veterans', 'Wounded Warriors Family Support', '20-1407520', 'To provide better quality of life to military personnel and their families wounded, injured or killed in Iraq & Afghanistan, and to provide financial funding to other veteran organizations with similar missions.', 'Omaha', 'Nebraska');


